"""Wizard-based flows for disk operations."""

from diskforge.ui.views.wizards.operations import (
    CreatePartitionWizard,
    FormatPartitionWizard,
    DeletePartitionWizard,
    CloneDiskWizard,
    ClonePartitionWizard,
    CreateBackupWizard,
    RestoreBackupWizard,
    RescueMediaWizard,
    ResizeMovePartitionWizard,
    MergePartitionsWizard,
    SplitPartitionWizard,
    ExtendPartitionWizard,
    ShrinkPartitionWizard,
    WipeWizard,
    PartitionRecoveryWizard,
    Align4KWizard,
    ConvertPartitionStyleWizard,
    SystemMigrationWizard,
)

__all__ = [
    "CreatePartitionWizard",
    "FormatPartitionWizard",
    "DeletePartitionWizard",
    "CloneDiskWizard",
    "ClonePartitionWizard",
    "CreateBackupWizard",
    "RestoreBackupWizard",
    "RescueMediaWizard",
    "ResizeMovePartitionWizard",
    "MergePartitionsWizard",
    "SplitPartitionWizard",
    "ExtendPartitionWizard",
    "ShrinkPartitionWizard",
    "WipeWizard",
    "PartitionRecoveryWizard",
    "Align4KWizard",
    "ConvertPartitionStyleWizard",
    "SystemMigrationWizard",
]
